/**
 * Single typed home for the pre-parsed custody chains of the featured works.
 *
 * The data itself lives in featured-provenance.json (committed, generated by
 * scripts/preparse-provenance.mjs — zero runtime Claude cost). Both the
 * /api/provenance route and the static /work/[slug] pages read through here
 * so the JSON's shape is asserted in exactly one place.
 */

import featuredProvenanceData from './featured-provenance.json'
import type { LocationEntry } from './types'

const FEATURED_PROVENANCE = featuredProvenanceData as Record<string, LocationEntry[]>

/** Pre-parsed ownership chain for a featured work, keyed `<source>:<id>`. */
export function getFeaturedChain(source: string, id: string): LocationEntry[] | undefined {
  return FEATURED_PROVENANCE[`${source}:${id}`]
}
